# Parameter domains (for input to GAMS solver)
parameter_domains = {}
# All
parameter_domains['cost_rgu'] = ['resource', 't']
parameter_domains['cost_rgd'] = ['resource', 't']
parameter_domains['cost_spr'] = ['resource', 't']
parameter_domains['cost_nsp'] = ['resource', 't']
parameter_domains['init_en'] = ['resource']
parameter_domains['init_status'] = ['resource']
parameter_domains['ramp_dn'] = ['resource']
parameter_domains['ramp_up'] = ['resource']
# Str
parameter_domains['chmax'] = ['resource', 't']
parameter_domains['dcmax'] = ['resource', 't']
parameter_domains['socmax'] = ['resource']
parameter_domains['socmin'] = ['resource']
parameter_domains['block_ch_mc'] = ['resource', 'offer_block', 't']
parameter_domains['block_dc_mc'] = ['resource', 'offer_block', 't']
parameter_domains['block_soc_mc'] = ['resource', 'offer_block', 't']
parameter_domains['block_ch_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_dc_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_soc_mq'] = ['resource', 'offer_block', 't']
parameter_domains['soc_end'] = ['resource']
parameter_domains['soc_begin'] = ['resource']
parameter_domains['eff_ch'] = ['resource']
parameter_domains['eff_dc'] = ['resource']
# Gen
parameter_domains['cost_su'] = ['resource', 't']
parameter_domains['cost_op'] = ['resource', 't']
parameter_domains['cost_sd'] = ['resource', 't']
parameter_domains['pgmin'] = ['resource']
parameter_domains['pgmax'] = ['resource']
parameter_domains['rgumax'] = ['resource']
parameter_domains['rgdmax'] = ['resource']
parameter_domains['block_g_mq'] = ['resource', 'offer_block']
parameter_domains['block_g_mc'] = ['resource', 'offer_block']
parameter_domains['min_uptime'] = ['resource']
parameter_domains['min_downtime'] = ['resource']
parameter_domains['init_downtime'] = ['resource']
parameter_domains['init_uptime'] = ['resource']
parameter_domains['outage'] = ['resource', 't']
# Ren
parameter_domains['pvmin'] = ['resource', 't']
parameter_domains['pvmax'] = ['resource', 't']
parameter_domains['block_r_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_r_mc'] = ['resource', 'offer_block', 't']
# Dem
parameter_domains['pdmin'] = ['resource', 't']
parameter_domains['pdmax'] = ['resource', 't']
parameter_domains['block_d_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_d_mv'] = ['resource', 'offer_block', 't']
# Vir
parameter_domains['block_dec_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_inc_mq'] = ['resource', 'offer_block', 't']
parameter_domains['block_v_mv'] = ['resource', 'offer_block', 't']
parameter_domains['block_v_mc'] = ['resource', 'offer_block', 't']

# Dictionary for parsing the storage attributes for ESPA-Comp
storage_attributes = {}
storage_attributes['imax'] = ['resource']
storage_attributes['imin'] = ['resource']
storage_attributes['vmax'] = ['resource']
storage_attributes['vmin'] = ['resource']
storage_attributes['ch_cap'] = ['resource']
storage_attributes['eff_coul'] = ['resource']
storage_attributes['eff_inv0'] = ['resource']
storage_attributes['eff_inv1'] = ['resource']
storage_attributes['eff_inv2'] = ['resource']
storage_attributes['voc0'] = ['resource']
storage_attributes['voc1'] = ['resource']
storage_attributes['voc2'] = ['resource']
storage_attributes['voc3'] = ['resource']
storage_attributes['chmax'] = ['resource']
storage_attributes['dcmax'] = ['resource']
storage_attributes['resis'] = ['resource']
storage_attributes['socmax'] = ['resource']
storage_attributes['socmin'] = ['resource']
storage_attributes['socref'] = ['resource']
storage_attributes['therm_cap'] = ['resource']
storage_attributes['temp_max'] = ['resource']
storage_attributes['temp_min'] = ['resource']
storage_attributes['temp_ref'] = ['resource']
storage_attributes['Utherm'] = ['resource']
storage_attributes['deg_DoD0'] = ['resource']
storage_attributes['deg_DoD1'] = ['resource']
storage_attributes['deg_DoD2'] = ['resource']
storage_attributes['deg_DoD3'] = ['resource']
storage_attributes['deg_DoD4'] = ['resource']
storage_attributes['deg_soc'] = ['resource']
storage_attributes['deg_therm'] = ['resource']
storage_attributes['deg_time'] = ['resource']
storage_attributes['cycle_life'] = ['resource']
storage_attributes['cost_EoL'] = ['resource']
storage_attributes['soc_capacity'] = ['resource']
storage_attributes['num_stack'] = ['resource']
